#!/usr/bin/env bash

readonly BIN="/usr/bin/varnishncsa"
readonly FORMAT="${VARNISH_VARNISHNCSA_FORMAT:-"%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-agent}i\""}"
readonly LOCK_FILE="/var/lock/subsys/varnishd-wrapper"
readonly NICE="/bin/nice"
readonly NICENESS="10"
readonly PID_PATH="/var/run/varnish/varnishncsa.pid"

readonly OPTIONS="-a -c -P ${PID_PATH} -F \"${FORMAT//\"/\\\"}\""

while true
do
	sleep 0.1
	[[ -e ${LOCK_FILE} ]] || break
done

eval "exec ${NICE} \
	-n ${NICENESS} \
	${BIN} \
	${OPTIONS}"
