# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
#
# Setup:
# Copy .env.example to .env and modify values as required.
# docker-compose down
# docker-compose build
#
# Run Default example:
# docker-compose up -d
#
# Check service logs:
# docker-compose logs -f -t varnish
#
# Usage:
# docker-compose exec varnish varnishadm
# docker-compose exec varnish varnishadm ban "req.url ~ (\\\.css|\\\.js)"
# docker-compose exec varnish varnishadm ban "req.url ~ ."
# docker-compose exec varnish varnishadm ban.list
# docker-compose exec varnish varnishlog -c -q 'ReqURL ~ "/$"'
# ------------------------------------------------------------------------------
version: "3.0"
networks:
  tier1:
    driver: "bridge"
  tier2:
    driver: "bridge"
    internal: true
services:
  varnish:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - "apache-php"
    environment:
      VARNISH_AUTOSTART_VARNISHNCSA_WRAPPER: "true"
      VARNISH_MAX_THREADS: "${VARNISH_MAX_THREADS}"
      VARNISH_MIN_THREADS: "${VARNISH_MIN_THREADS}"
      VARNISH_OPTIONS: "${VARNISH_OPTIONS}"
      VARNISH_STORAGE: "${VARNISH_STORAGE}"
      VARNISH_THREAD_TIMEOUT: "${VARNISH_THREAD_TIMEOUT}"
      VARNISH_TTL: "${VARNISH_TTL}"
      VARNISH_VARNISHNCSA_FORMAT: "${VARNISH_VARNISHNCSA_FORMAT}"
      VARNISH_VARNISHNCSA_OPTIONS: "${VARNISH_VARNISHNCSA_OPTIONS}"
      VARNISH_VCL_CONF: "${VARNISH_VCL_CONF}"
    image: "jdeathe/centos-ssh-varnish:latest"
    networks:
      - "tier1"
      - "tier2"
    ports:
      # HTTP protocol
      - "8000:80"
      # PROXY protocol
      - "8500:8443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    tty: true
    ulimits:
      memlock: 82000
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
  apache-php:
    depends_on:
      - "memcached"
    environment:
      APACHE_CUSTOM_LOG_LOCATION: "/dev/null"
      APACHE_ERROR_LOG_LOCATION: "/dev/stderr"
      APACHE_LOAD_MODULES: "rewrite_module"
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:3.2.0"
    networks:
      tier2:
        aliases:
          - "httpd_1"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  memcached:
    environment:
      MEMCACHED_CACHESIZE: "32"
      MEMCACHED_MAXCONN: "1024"
    image: "jdeathe/centos-ssh-memcached:2.2.1"
    networks:
      - "tier2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
