# ------------------------------------------------------------------------------
# Ref: https://docs.docker.com/compose/compose-file/
#
# docker-compose down
# docker-compose build
# docker-compose up -d
#
# Access Logs
# docker-compose exec varnish varnishncsa
#
# CLI
# docker-compose exec varnish varnishadm
# ------------------------------------------------------------------------------
version: "3.0"
networks:
  tier1:
    driver: "bridge"
  tier2:
    driver: "bridge"
    internal: true
services:
  varnish:
    build:
      context: "."
      dockerfile: "Dockerfile"
    depends_on:
      - "httpd_1"
    environment:
      VARNISH_STORAGE: "malloc,256M"
      VARNISH_MAX_THREADS: "2048"
      VARNISH_MIN_THREADS: "1024"
    image: "jdeathe/centos-ssh-varnish:latest"
    networks:
      - "tier1"
      - "tier2"
    ports:
      # HTTP protocol
      - "80:80"
      # PROXY protocol
      - "8443:8443"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
    tty: true
    ulimits:
      memlock: 82000
      nofile:
        soft: 524288
        hard: 1048576
      nproc: 65535
  httpd_1:
    depends_on:
      - "memcached"
    environment:
      APACHE_MOD_SSL_ENABLED: "false"
      APACHE_MPM: "event"
      APACHE_SERVER_ALIAS: "app.local"
      APACHE_SERVER_NAME: "www.app.local"
      PHP_OPTIONS_SESSION_SAVE_HANDLER: "memcached"
      PHP_OPTIONS_SESSION_SAVE_PATH: "memcached:11211"
    image: "jdeathe/centos-ssh-apache-php:2.2.6"
    networks:
      tier2:
        aliases:
          - "httpd_1"
          - "web_1"
    restart: "always"
    sysctls:
      net.core.somaxconn: "1024"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"
  memcached:
    environment:
      MEMCACHED_CACHESIZE: "32"
      MEMCACHED_MAXCONN: "2048"
    image: "jdeathe/centos-ssh-memcached:1.1.3"
    networks:
      - "tier2"
    restart: "always"
    sysctls:
      net.core.somaxconn: "2048"
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.route.flush: "1"