#!/usr/bin/env bash

function set_varnish_vcl_conf ()
{
	local VALUE="${1:-}"
	local PLAIN_TEXT_PATTERN='.*vcl 4.0;.*'
	local BASE64_PATTERN='^[A-Za-z0-9/+=]*$'

	if [[ -n ${VALUE} ]] && [[ ! -s ${VALUE} ]]; then
		# Decode base64 encoded values
		if [[ ${VALUE} =~ ${BASE64_PATTERN} ]]; then
			VALUE="$(
				base64 -d -i <<< "${VALUE}"
			)"
		fi

		if [[ ! ${VALUE} =~ ${PLAIN_TEXT_PATTERN} ]]; then
			printf -- \
				'ERROR: Invalid VCL File\n' \
				>&2
			sleep 0.1
			exit 1
		fi

		printf \
			-- '%s' \
			"${VALUE}" \
		> /etc/services-config/varnish/docker-default.vcl

		unset VARNISH_VCL_CONF
	fi
}

set_varnish_vcl_conf "${VARNISH_VCL_CONF}"

VARNISHD=/usr/sbin/varnishd
NICE=/bin/nice

DAEMON_OPTS="-j unix,user=varnish,ccgroup=varnish
 -F
 -P /var/run/varnish.pid
 -a 0.0.0.0:80
 -a 0.0.0.0:8443
 -f ${VARNISH_VCL_CONF:-/etc/varnish/docker-default.vcl}
 -T 127.0.0.1:6082
 -t ${VARNISH_TTL:-120}
 -p thread_pool_min=${VARNISH_MIN_THREADS:-50}
 -p thread_pool_max=${VARNISH_MAX_THREADS:-1000}
 -p thread_pool_timeout=${VARNISH_THREAD_TIMEOUT:-120}
 -S /etc/varnish/secret
 -s ${VARNISH_STORAGE:-file,/var/lib/varnish/varnish_storage.bin,1G}
"

NICENESS=${VARNISH_NICENESS:-10}

printf -- \
	"Starting Varnish Cache: \n%s\n" \
	"${DAEMON_OPTS}"

exec ${NICE} \
	-n ${NICENESS} \
	${VARNISHD} \
	${DAEMON_OPTS}
