#!/usr/bin/env bash

VARNISHD=/usr/sbin/varnishd
NICE=/bin/nice

DAEMON_OPTS="-j unix,user=varnish,ccgroup=varnish
 -F
 -P ${PIDFILE:-/var/run/varnish.pid}
 -a ${VARNISH_LISTEN_ADDRESS:-0.0.0.0}:${VARNISH_LISTEN_PORT:-80}
 -f ${VARNISH_VCL_CONF:-/etc/varnish/docker-default.vcl}
 -T ${VARNISH_ADMIN_LISTEN_ADDRESS:-127.0.0.1}:${VARNISH_ADMIN_LISTEN_PORT:-6082}
 -t ${VARNISH_TTL:-120}
 -p thread_pool_min=${VARNISH_MIN_THREADS:-50}
 -p thread_pool_max=${VARNISH_MAX_THREADS:-1000}
 -p thread_pool_timeout=${VARNISH_THREAD_TIMEOUT:-120}
 -S ${VARNISH_SECRET_FILE:-/etc/varnish/secret}
 -s ${VARNISH_STORAGE:-file,/var/lib/varnish/varnish_storage.bin,1G}
"

NICENESS=${VARNISH_NICENESS:-10}

printf -- \
	"Starting Varnish Cache: \n%s\n" \
	"${DAEMON_OPTS}"

exec ${NICE} \
	-n ${NICENESS} \
	${VARNISHD} \
	${DAEMON_OPTS}
