#!/usr/bin/env bash

VARNISHD=/usr/sbin/varnishd
NICE=/bin/nice

DAEMON_OPTS="-F
 -P ${PIDFILE:-/var/run/varnish.pid}
 -a ${VARNISH_LISTEN_ADDRESS:-0.0.0.0}:${VARNISH_LISTEN_PORT:-80}
 -f ${VARNISH_VCL_CONF:-/etc/varnish/docker-default.vcl}
 -T ${VARNISH_ADMIN_LISTEN_ADDRESS:-127.0.0.1}:${VARNISH_ADMIN_LISTEN_PORT:-6082}
 -t ${VARNISH_TTL:-120}
 -w ${VARNISH_MIN_THREADS:-50},${VARNISH_MAX_THREADS:-1000},${VARNISH_THREAD_TIMEOUT:-120}
 -u varnish -g varnish
 -S ${VARNISH_SECRET_FILE:-/etc/varnish/secret}
 -s ${VARNISH_STORAGE:-file,/var/lib/varnish/varnish_storage.bin,1G}
"
NICENESS=${VARNISH_NICENESS:-10}

# ulimit settings require docker containers to be run with --privileged
# https://github.com/dotcloud/docker/issues/4717
# ulimit -n ${NFILES:-131072}
# ulimit -l ${MEMLOCK:-82000}
# ulimit -u ${NPROCS:-unlimited}

sprintf --- "Starting Varnish Cache: \n%s\n" "${DAEMON_OPTS}"

exec ${NICE} \
	-n ${NICENESS} \
	${VARNISHD} \
	${DAEMON_OPTS}
