# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------
readonly SERVICE_UNIT_ENVIRONMENT_KEYS="
 DOCKER_CONTAINER_OPTS
 DOCKER_IMAGE_PACKAGE_PATH
 DOCKER_IMAGE_TAG
 DOCKER_PORT_MAP_TCP_80
 DOCKER_PORT_MAP_TCP_8443
 SYSCTL_NET_CORE_SOMAXCONN
 SYSCTL_NET_IPV4_IP_LOCAL_PORT_RANGE
 SYSCTL_NET_IPV4_ROUTE_FLUSH
 ULIMIT_MEMLOCK
 ULIMIT_NOFILE
 ULIMIT_NPROC
 VARNISH_AUTOSTART_VARNISHD_WRAPPER
 VARNISH_AUTOSTART_VARNISHNCSA_WRAPPER
 VARNISH_MAX_THREADS
 VARNISH_MIN_THREADS
 VARNISH_OPTIONS
 VARNISH_STORAGE
 VARNISH_THREAD_TIMEOUT
 VARNISH_TTL
 VARNISH_VARNISHNCSA_FORMAT
 VARNISH_VARNISHNCSA_OPTIONS
 VARNISH_VCL_CONF
"

readonly SERVICE_UNIT_REGISTER_ENVIRONMENT_KEYS="
 REGISTER_ETCD_PARAMETERS
 REGISTER_TTL
 REGISTER_UPDATE_INTERVAL
"

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------
SERVICE_UNIT_INSTALL_TIMEOUT="${SERVICE_UNIT_INSTALL_TIMEOUT:-5}"
